baseurl = "/"
languageCode = "ja-JP"
title = "R Club"
theme = "hugo-xmin"
googleAnalytics = "UA-125805158-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"
    drill = "/drill/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Schedule"
    url = "/schedule"
    weight = 2
[[menu.main]]
    name = "Textbook"
    url = "/categories/text/"
    weight = 3
[[menu.main]]
    name = "Data"
    url = "/data/"
    weight = 4
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 6
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 7
[[menu.main]]
    name = "RSS"
    url = "/index.xml"

[params]
    description = "R Club at Osaka Prefecture University."
    footer = "&copy; [OPU R Club](https://opur.club/) 2018 | [Github](https://github.com/opueco)"
    custom_css = ["css/custom.css"]
