[context.production.environment]
  HUGO_VERSION = "0.48"

[context.deploy-preview]
  command = "hugo --buildFuture"
  [context.deploy-preview.environment]
    HUGO_VERSION = "0.48"

[context.branch-deploy]
  command = "hugo --buildFuture"
  [context.branch-deploy.environment]
    HUGO_VERSION = "0.48"
    